### ISSUE TITLE
 [LFS error] Help with getting data

### ISSUE THREAD

**Issue by mittalgovind** [chaowentao/LAGAN#1]
`git-lfs fetch sketches.zip`

`fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/chaowentao/LAGAN.git/info/lfs'
`

**Comment by chaowentao** [comment]
@mittalgovind  Sorry, please give me your email. I will send sketches data to you.

**Comment by mittalgovind** [comment]
its mittal@nyu.edu

**Comment by jzxr** [comment]
I am also facing this error, could you email me too? 2001576@sit.singaporetech.edu.sg 
Appreciate it!
